#!/usr/bin/env bash
#
file_path="school"

if [ -e "$file_path" ]; then   # Start of the first block
	  echo "School file exists"

	    if [ -s "$file_path" ]; then
		        echo "School file is not empty"
			  else
				      echo "School file is empty"
				        fi

					  if [ -f "$file_path" ]; then
						      echo "School is a regular file"
						        fi

						else                          # Start of the else block
							  echo "School file does not exist"
fi                            # End of the else block

